### ISSUE TITLE
Sugerencias

### ISSUE THREAD

**Issue by cinemascop89** [Fondeadora/python-service-template#1]
### Paquetes predefinidos:

requirements.txt:

* `boto` ya que la mayoria de los servicios van a necesitar llamar a algun servicio de aws

package.json:

*  `serverless-offline-sqs` seria muy util para los servicios que se comunicaran a traves de mensajes

Estos son los paquetes que se me ocurren que vamos a necesitar desde un principio, se me esta escapando algun otro?

### Estructura del proyecto

Seria conveniente tener todo el codigo python separado en su propio package (no se me ocurre un buen nombre para ponerle, capaz `service` o `src`?)

Algo asi:

```
requirements.txt
services
  +- __init__.py
  +- models.py
  +- handlers
       +- __init__.py
       +- handler1.py
       +- handler2.py
```

Capaz que el template puede tener el package `handlers` vacio o con el handler hello world que te da serverless, y el modulo `models` vacio tambien

Que opinan?

**Comment by froysm** [comment]
Ya actualicé el repo con las sugerencias que hiciste (https://github.com/Fondeadora/python-service-template/commit/7329bfc255cc4205157e050c8a8c6152d618622f).

`boto3` lo agregué en requirements-dev.txt porque esa librería está disponible por default en el environment de lambda (https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html), así que no es necesario agregarla en los requirements de producción.

Hablando de los requirements, agregué el plugin `serverless-python-requirements` para empaquetar los requirements para producción al momento de ejecutar `sls deploy`.
